name: Auto Merge

on:
  workflow_run:
    # This workflow will run when the "Deploy Preview" workflow completes.
    # Adjust "Deploy Preview" to the exact name of the workflow that needs to pass before automerge.
    workflows: ["Deploy Preview"]
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    # This condition ensures the automerge job only runs if the triggering workflow_run (e.g., Deploy Preview)
    # completed successfully.
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write # Needed to merge the PR and delete the branch
      pull-requests: write # Needed to interact with the PR (read details, merge)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # A token is needed to interact with the repository, including fetching PR details
          # and performing the merge operation.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Use a recent stable Python 3 version

      - name: Install dependencies
        run: pip install PyGithub # Install the PyGithub library for interacting with the GitHub API

      - name: Run automerge script
        # The script will be run with environment variables providing necessary context
        env:
          # GITHUB_TOKEN is required for authentication with the GitHub API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PR_NUMBER is retrieved from the workflow_run event, specifically the first pull request associated
          # with the completed workflow run.
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          # GITHUB_REPOSITORY provides the context of the current repository (e.g., 'owner/repo-name')
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python .github/scripts/automerge.py

