name: Sync Discussion to Blog Post

on:
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created]

jobs:
  sync_and_publish:
    # Only run if the discussion is in a specific category (e.g., 'News', 'Blog Posts')
    # IMPORTANT: User needs to update 'YOUR_DISCUSSION_CATEGORY' to their desired category name.
    # If the category name has spaces, it should be enclosed in quotes.
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repo
      discussions: read # Required to read discussion content

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML google-generativeai

      # ---- CORRECTED STEP ----
      - name: Set Discussion Node ID
        id: set_discussion_id
        run: |
          echo "Event triggered: ${{ github.event_name }}"
          # The discussion object is at the top level for both 'discussion' and 'discussion_comment' events.
          # This single line works for both triggers.
          echo "DISCUSSION_NODE_ID=${{ github.event.discussion.node_id }}" >> $GITHUB_ENV

      - name: Debug Discussion Node ID
        run: |
          echo "DISCUSSION_NODE_ID from env is: ${{ env.DISCUSSION_NODE_ID }}"
          
      - name: Run Sync Script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_DISCUSSION_ID: ${{ env.DISCUSSION_NODE_ID }}
        run: python sync_discussions.py

      - name: Commit and Push Blog Post
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          # Check if there are changes in _posts/
          if ! git diff --quiet _posts/; then
            git add _posts/*.md
            git commit -m "Automated: Add/update blog post from discussion '${{ github.event.discussion.title }}'"
            git push
          else
            echo "No changes to commit in _posts/ directory."
          fi
