name: Sync Discussion to Blog Post

on:
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created]

jobs:
  sync_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repo
      discussions: read # Required to read discussion content

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML google-generativeai

      - name: Set Discussion Node ID
        id: set_discussion_id
        run: |
          echo "Event triggered: ${{ github.event_name }}"
          echo "DISCUSSION_NODE_ID=${{ github.event.discussion.node_id }}" >> $GITHUB_ENV

      - name: Debug Discussion Node ID
        run: |
          echo "DISCUSSION_NODE_ID from env is: ${{ env.DISCUSSION_NODE_ID }}"
          
      - name: Run Sync Script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_DISCUSSION_ID: ${{ env.DISCUSSION_NODE_ID }}
        run: python sync_discussions.py

      # --- CORRECTED COMMIT & PUSH STEP ---
      # This version correctly handles both new (untracked) and modified files.
      - name: Commit and Push Blog Post
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          
          echo "### Staging any new or modified files in _posts/ ###"
          # This command stages both new and modified files.
          # It won't fail if there are no files that match.
          git add _posts/*.md
          
          echo "### Checking if there is anything to commit ###"
          # 'git diff --staged --quiet' checks if the staging area is empty.
          # The '!' reverses the exit code, so the block runs if there are staged changes.
          if ! git diff --staged --quiet; then
            echo "✅ Staged changes found. Proceeding with commit."
            git commit -m "Automated: Add/update blog post from discussion '${{ github.event.discussion.title }}'"
            git push
          else
            echo "❌ No new or modified blog posts found to commit."
          fi
